baseURL = 'https://iony-systems.com/'
languageCode = 'fr'
title = 'IONY SYSTEMS'
theme = 'mana-theme'

[params]
  description = "Studio de développement d'applications mobiles iOS & Android"
  tabTitle = "IONY SYSTEMS — Studio de développement mobile iOS & Android"
  author = "Iony Systems"

  [params.social]
    linkedin = "https://www.linkedin.com/in/remy-dionisio"
    email = "contact@iony-systems.com"

  [params.copyright]
    owner = "Iony Systems"

# Menu de navigation
[[menus.main]]
  name = "Services"
  url = "/#services"
  weight = 10

[[menus.main]]
  name = "À propos"
  url = "/#about"
  weight = 20

[[menus.main]]
  name = "Projets"
  url = "/#projects"
  weight = 30

[[menus.main]]
  name = "Contact"
  url = "/#contact"
  weight = 40


[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "catppuccin-macchiato"
